name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'  # or whatever version you use

    - name: Generate coverage using Makefile
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./pkg/crdt ./internal/crypto

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # required for private repos
        files: coverage.txt
        fail_ci_if_error: true
