name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Label of the container job
  runner-job:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.5

    - name: Build
      run: make 

    - name: Test
      run: TZ=Europe/Stockholm make test
      env:
        MY_EXAMPLE_ENV: examplehost:port
